### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SCKelemen** [playlyfe/go-graphql#15]
Is there any documentation? 

Especially on using this with a router.

**Comment by kumarharsh** [comment]
The README offers a brief code-cum-documentation of the library. We need to do some work to make better documentation. @SCKelemen what kind of router are you using btw?

**Comment by SCKelemen** [comment]
I apologize for the delay. I thought I had already replied.

I am using quo-vadis. https://github.com/jackc/quo_vadis

Thanks!

**Comment by kumarharsh** [comment]
We're using `Echo`

It's very simple, just mount your graphql request server on the `/graphql` POST route.

```go
func NewServer() *echo.Echo {
  ...
  server.Post("/graphql", graphQLHandler)
}

func graphQLHandler(context echo.Context) error {
    ...
    // setup executor here
    ...
    body, err := ioutil.ReadAll(context.Request().Body())
    if err != nil {
        panic(err)
    }
    var data map[string]interface{}
    if err := json.Unmarshal(body, &data); err != nil {
        panic(err)
    }
    query := data["query"]
    variables := data["variables"]
    result, err := executor.Execute(context, query, variables, "")
    if err != nil {
        panic(err)
    }
    fmt.Printf("%v", result)
    // return result
}
```
