### ISSUE TITLE
Parallel resolvers

### ISSUE THREAD

**Issue by paralin** [playlyfe/go-graphql#17]
https://github.com/playlyfe/go-graphql/blob/master/executor.go#L1043

Should be easy enough to use a channel for results and goroutines to launch each sub-resolver on an object.

**Comment by paralin** [comment]
Just noticed you've done it.. Interesting, will test

**Comment by atrniv** [comment]
Yes, all queries are resolved in parallel by default, unless you enable the Debug false on the executor instance using `executor.Debug = false`. I've still not figured out how to get non-cryptic stack traces out of parallel go-routines so I kept the debug flag to trace down panics within resolvers more easily.

**Comment by paralin** [comment]
Code's a bit messy - you pass true to isParallel everywhere. Would recommend cleaning it up a bit.

Otherwise, nice work!
