### ISSUE TITLE
Hide __typename field

### ISSUE THREAD

**Issue by maksimkurb** [playlyfe/go-graphql#20]
I have noticed that every object has `__typename` field in GraphiQL documentation
![2017-01-05 15-48-01](https://cloud.githubusercontent.com/assets/1351924/21679583/61edc4c2-d35e-11e6-8b36-d254d7aa3a8a.png)

I think this field is not supposed to be visible, confirm me if I wrong

**Comment by kumarharsh** [comment]
There are situations when __typename is very useful, such as when working with union types, where it's hard to tell which type of data we'll be getting back.

Some more information about the usefulness of this field are mentioned in the official documentation here: http://graphql.org/learn/queries/#meta-fields

**Comment by maksimkurb** [comment]
Anyway, my PR only hides this field from introspection query, so it not
displayed in graphiql IDE but it can be queried

05.01.2017 22:58 пользователь "Kumar Harsh" <notifications@github.com>
написал:
