### ISSUE TITLE
Integration with react-relay

### ISSUE THREAD

**Issue by krypton97** [playlyfe/go-graphql#22]
I've been looking for some examples, but couldn't find anything. Since the docs lacks a bit, I was wondering if it could be used with react-relay. An workaround would be using the apollo-client which is compatible with every backend language, but is not as great as relay is...If there's anyone that managed to do so, I'd be gladful for any source code ;)

**Comment by kumarharsh** [comment]
We're using this with react-relay. What do you want to know exactly?

**Comment by krypton97** [comment]
Yeah, I'm using webpack 2 with node js modules on frontend. I know there is another graphql implementation, but doesn't work with relay out of the box, that's why I was asking. Thank you again for the support and for letting me know about  @playlyfe/gql library :)
