### ISSUE TITLE
Unexpected behavior with graphql

### ISSUE THREAD

**Issue by krypton97** [playlyfe/go-graphql#25]
I was playing with the API and after a couple of tries I've noticed an issue with the returning value. I'll post here what my code looks like:

`
package main

import (
	"net/http"

	"fastQL/graphiql"

	"github.com/krypton97/HandleGraphQL"
	"github.com/playlyfe/go-graphql"
   )

 //Tea type
 type Tea struct {
	 name         string
	 steepingTime int
 }

//Teas type
type Teas []*Tea

func main() { 

	schema := `
	type Tea {
		name: String
		steepingTime: Int
	}

	type QueryRoot {
		teas: [Tea]
	}
	`
	resolvers := map[string]interface{}{}

	resolvers["QueryRoot/teas"] = func(params *graphql.ResolveParams) (interface{}, error) {
		return []map[string]interface{}{
			{
				"__typename":   "Tea",
				"name":         "Earl Grey Blue Star",
				"steepingTime": 5,
			},

			{
				"__typename":   "Tea",
				"name":         "Milk Oolong",
				"steepingTime": 3,
			},
			{
				"__typename":   "Tea",
				"name":         "Gunpowder Golden Temple",
				"steepingTIme": 2,
			},
			{
				"__typename":   "Tea",
				"name":         "Assam Hatimara",
				"steepingTime": 5,
			},
		}, nil
	}

	executor, err := graphql.NewExecutor(schema, "QueryRoot", "", resolvers)

	executor.ResolveType = func(value interface{}) string {
		if object, ok := value.(map[string]interface{}); ok {
			return object["__typename"].(string)
		}
		return ""
	}

	if err != nil {
		panic(err)
	}

	api := handler.New(&handler.Config{
		Executor: executor,
		Context:  "",
		Pretty:   true,
	})

	graphiql := graphiql.New("/graphql")

	http.Handle("/graphql", api)
	http.Handle("/query", graphiql)
	http.ListenAndServe(":3000", nil)
}
`

Running the following code return the following:

`
{
  "data": {
    "teas": [
      {
        "name": "Earl Grey Blue Star",
        "steepingTime": 5
      },
      {
        "name": "Milk Oolong",
        "steepingTime": 3
      },
      {
        "name": "Gunpowder Golden Temple",
        "steepingTime": null
      },
      {
        "name": "Assam Hatimara",
        "steepingTime": 5
      }
    ]
  }
}

`

As you can see, the third field returns a null value, but the rest of them are ok. I can't seem to figure it out, any reason for that?

**Comment by atrniv** [comment]
you have a typo  in your returned object key. Its `steepingTIme` instead of `steepingTime`
