### ISSUE TITLE
Bug with deep map resolvers!

### ISSUE THREAD

**Issue by krypton97** [playlyfe/go-graphql#30]
Looking to implement pagination with this library and I found a strange bug. By strange I mean that the fields are recognised, but the value is not returned. This is the code I have:

	package data
	
	import "github.com/playlyfe/go-graphql"
	import "fmt"
	
	var courses = map[string]map[string][]map[string]interface{}{
		"linkConnection": {
			"edges": {
				{
					"cursor": "YXJyYXljb25uZWN0aW9uOjA=",
					"node": map[string]string{
						"id":        "507f191e810c19729de860ea",
						"title":     "RelayJS course",
						"url":       "https://relay.cool.com/",
						"createdAt": "1974-08-07T11:53:39.056Z",
					},
				},
				{
					"cursor": "YXJyYXljb25uZWN0aW9uOjE=",
					"node": map[string]string{
						"id":        "58bc29705d58db311b3d1d85",
						"title":     "test link",
						"url":       "test.com",
						"createdAt": "1974-08-07T11:53:39.055Z",
					},
				},
				{
					"cursor": "YXJyYXljb25uZWN0aW9uOjI=",
					"node": map[string]string{
						"id":        "507f1f77bcf86cd799439011",
						"title":     "ReactJS main course",
						"url":       "https://mlab.com/databases/mongo/",
						"createdAt": "1974-08-07T11:53:39.054Z",
					},
				},
			},
		},
	}

	var Schema = `

		type Query {
			node(id: ID!): Node
			store: Store
		}

		type Mutation {
			createLink(input: CreateLinkInput!): CreateLinkPayload
		}
		
		interface Node {
			id: ID!
		}

		type Store implements Node {
			id: ID!
			linkConnection(after: String, first: Int, before: String, last: Int, query: String): LinkConnection
		}

		input CreateLinkInput {
			title: String!
			url: String!
			clientMutationId: String
		}

		type CreateLinkPayload {
			linkEdge: LinkEdge
			store: Store
			clientMutationId: String
		}

		type Link {
			id: ID!
			title: String
			url: String
			createdAt: String
		}

		type LinkConnection {
			pageInfo: PageInfo!
			edges: [LinkEdge]
		}

		type LinkEdge {
			node: Link
			cursor: String!
		}
		
		type PageInfo {
			hasNextPage: Boolean!
			hasPreviousPage: Boolean!
			startCursor: String
			endCursor: String
		}
    `

	var Resolvers = map[string]interface{}{
		"Query/store": func(p *graphql.ResolveParams) (interface{}, error) {
			return courses, nil
		},
		"Store/linkConnection": func(p *graphql.ResolveParams) (interface{}, error) {
			return courses["linkConnection"], nil
		},
		"LinkConnection/edges": func(p *graphql.ResolveParams) (interface{}, error) {
			fmt.Println(courses["linkConnection"]["edges"][0]["node"])
			return courses["linkConnection"]["edges"], nil
		},
	}

and the output on graphiql looks like this

	{
	  "data": {
	    "store": {
	      "linkConnection": {
	        "edges": [
	          {
	            "cursor": "YXJyYXljb25uZWN0aW9uOjA=",
	            "node": {
	              "createdAt": null,
	              "title": null,
	              "url": null
	            }
	          },
	          {
	            "cursor": "YXJyYXljb25uZWN0aW9uOjE=",
	            "node": {
	              "createdAt": null,
	              "title": null,
	              "url": null
	            }
	          },
	          {
	            "cursor": "YXJyYXljb25uZWN0aW9uOjI=",
	            "node": {
	              "createdAt": null,
	              "title": null,
	              "url": null
	            }
	          }
	        ]
	      }
	    }
	  }
	}

I might be doind it wrong, but since the fields are recognised, it makes me think about it..

**Comment by krypton97** [comment]
I found the solution and it kinda surprise me. After testing some particular cases, I found that the type of the node map should be `map[string]interface{}` not `map[string]string` ;)

**Comment by kumarharsh** [comment]
@krypto97 It's the go code above which is buggy. You've defined `courses` as `map[string]map[string][]map[string]interface{}`, but then have defined the nested `node` as the incompatible `map[string]string`. You'll have to change either one of those.

For example, change the type for courses to `map[string]map[string][]map[string]string`. Or better yet, don't even define the type, use `var courses := ....` syntax, and let go auto-infer the type.

**Comment by krypton97** [comment]
@kumarharsh  if I change the courses type to `map[string]map[string][]map[string]string` it won't recognise node since is not a `string`, but a `map[string]interface{}`. so I need to use the `interface{}` type. Can't use `:=` because it's an exported file. Other than that after the changes works good to me, I don't think it's a bad practice..
