### ISSUE TITLE
Project status in Readme.MD

### ISSUE THREAD

**Issue by lming** [playlyfe/go-graphql#8]
Hi,

I really like your implementation that defines gql in text! I am hoping to use the package in our project but it's not clear to me what's the status of this package. Could you put the status in Readme.MD? e.g. It's production ready, beta, alpha or WIP, graphQL spec supported version?

Thanks!
Ming

**Comment by lming** [comment]
I skimmed through code and tests (especially executor_test.go) and found the implementation is very solid. May want to put the status in README then submit this awesome package in https://github.com/chentsulin/awesome-graphql :)

**Comment by kumarharsh** [comment]
We are using the package in production in a closed-source project ourselves right now, and it's solid.

Thank you for your suggestion, will update the status after evaluating the production-readiness for third-party usage.

**Comment by lming** [comment]
Thanks for the update! Glad to know that it's in production already!

**Comment by pyros2097** [comment]
@lming I thought of putting here https://github.com/chentsulin/awesome-graphql but then we have zero documentation so they won't accept it until we add some.
The library is rock solid and production ready. We use it in heavy workloads and is highly performant.
But there are somethings missing like validation and stuff like that .. I'll add it in the readme. It implements the GraphQL October 2015 Spec but not completely though.
And for status I guess we need to add CI (I'll see if I can take it from the other graphql lib)

**Comment by lming** [comment]
@pyros2097 thank you for the detailed confirmation! I'll use it for my coming project. I have been debated between Go and nodejs, this package helps me to make decision to stay with Go.

btw in readme, "schema" in this line should be a query.
result, err := executor.Execute(context, schema, variables, "")

Again, I appreciate you and your company release this high quality library!

**Comment by pyros2097** [comment]
@lming Thanks for the headsUp. Anyways I would suggest not to go with nodejs as maintaining large codebases in it is very difficult and not scalable. We originally used nodejs and graphql-js for a month on our new product but then scrapped it as we face many issues (especially with promises and async behavior) and wanted compiled executables for our on premise deployments.

**Comment by pyros2097** [comment]
And BTW I've actually created a framework over this called GQX which I still haven't released maybe when I get some time I'll release it. It allows you to compose the grapqhl schema using structs.

**Comment by lming** [comment]
@pyros2097 I totally agree that nodejs project is too hard to maintain going forward. Golang is my go to language if the key library is available :)

GQX sounds very interesting! Looking forward to seeing it being released. Thanks!
